# Generated by Django 2.2 on 2020-02-09 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Titulo')),
                ('solution', models.TextField(verbose_name='Solucion')),
                ('evaluation_text', models.TextField(verbose_name='Texto de evaluacion')),
            ],
            options={
                'verbose_name': 'Examen',
                'verbose_name_plural': 'Examenes',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=10, verbose_name='Palabra')),
                ('prefix', models.CharField(max_length=30, verbose_name='Prefijo')),
                ('solution', models.CharField(max_length=10, verbose_name='Solucion')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Exam', verbose_name='Examen')),
            ],
            options={
                'verbose_name': 'Palabra',
                'verbose_name_plural': 'Palabras',
            },
        ),
    ]
