# Generated by Django 2.2 on 2020-02-09 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='solution',
        ),
        migrations.AddField(
            model_name='word',
            name='position',
            field=models.IntegerField(default=0, verbose_name='position'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exam',
            name='evaluation_text',
            field=models.TextField(verbose_name='Texto de evaluación'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='solution',
            field=models.TextField(verbose_name='Solución'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Título'),
        ),
    ]
