# Generated by Django 2.2 on 2020-02-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_auto_20200216_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='level',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1')], default=('A1', 'A1'), max_length=2),
        ),
    ]
